CREATE SEQUENCE reader_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE department_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE library_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE storage_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE bookPosition_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE author_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE publication_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE category_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE subject_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE edition_seq INCREMENT 50 START 70 MINVALUE 1;

CREATE SEQUENCE company_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE profession_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE staff_seq INCREMENT 50 START 50 MINVALUE 1;

CREATE SEQUENCE distribution_seq INCREMENT 50 START 60 MINVALUE 1;
